In [2]:
import numpy as np


In [48]:
counter=1
list1=[1,4,7]
list2=[1,2,3,4,5,6,7,8,9]
list4=[]
list5=[]
a=[1,2,3]
b=[4,5,6]
c=[7,8,9]
d=[1,4,7]
e=[2,5,8]
f=[3,6,9]
g=[1,5,9]
h=[3,5,7]
    

while counter<10:
    
    counter=counter+1
    mat=np.array(list2)
    print(mat.reshape(3,3))
    user_input=int(input("which position would you like to take:"))
    if counter%2==0:
        if user_input in list2:
            for n,i in enumerate(list2):
                if i==user_input:
                    list2[n]="X"
                    list4.append(n+1)
                    result1 =  all(elem in list4  for elem in a)
                    result2 =  all(elem in list4  for elem in b)
                    result3 =  all(elem in list4  for elem in c)
                    result4 =  all(elem in list4  for elem in d)
                    result5 =  all(elem in list4  for elem in e)
                    result6 =  all(elem in list4  for elem in f)
                    result7 =  all(elem in list4  for elem in g)
                    result8 =  all(elem in list4  for elem in h)
        if len(list4)==5:
            print("Draw")
        else:
            if result1==True:
                print("player 1 won")
                break
            elif result2==True:
                print("player 1 won")
                break
            elif result3==True:
                print("player 1 won")
                break
            elif result4==True:
                print("player 1 won")
                break
            elif result5==True:
                print("player 1 won")
                break
            elif result6==True:
                print("player 1 won")
                break
            elif result7==True:
                print("player 1 won")
                break
            elif result8==True:
                print("player 1 won")
                break








                    
    else:
        if user_input in list2:
            for n,i in enumerate(list2):
                if i==user_input:
                    list2[n]="O"
                    
                    list5.append(n+1)
                    result1 =  all(elem in list5  for elem in a)
                    result2 =  all(elem in list5  for elem in b)
                    result3 =  all(elem in list5  for elem in c)
                    result4 =  all(elem in list5  for elem in d)
                    result5 =  all(elem in list5  for elem in e)
                    result6 =  all(elem in list5  for elem in f)
                    result7 =  all(elem in list5  for elem in g)
                    result8 =  all(elem in list5  for elem in h)
            if result1==True:
                print("player 2 won")
                break
            elif result2==True:
                print("player 2 won")
                break
            elif result3==True:
                print("player 2 won")
                break
            elif result4==True:
                print("player 2 won")
                break
            elif result5==True:
                print("player 2 won")
                break
            elif result6==True:
                print("player 2 won")
                break
            elif result7==True:
                print("player 2 won")
                break
            elif result8==True:
                print("player 2 won")
                break

     
    


[[1 2 3]
 [4 5 6]
 [7 8 9]]
which position would you like to take:4
[['1' '2' '3']
 ['X' '5' '6']
 ['7' '8' '9']]
which position would you like to take:1
[['O' '2' '3']
 ['X' '5' '6']
 ['7' '8' '9']]
which position would you like to take:5
[['O' '2' '3']
 ['X' 'X' '6']
 ['7' '8' '9']]
which position would you like to take:2
[['O' 'O' '3']
 ['X' 'X' '6']
 ['7' '8' '9']]
which position would you like to take:7
[['O' 'O' '3']
 ['X' 'X' '6']
 ['X' '8' '9']]
which position would you like to take:3
player 2 won
